name: Build and Deploy JobPortal API to Azure

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore ./JobPortal.API/JobPortal.API.csproj

      - name: Build
        run: dotnet build ./JobPortal.API/JobPortal.API.csproj --configuration Release --no-restore

      - name: Publish (self-contained)
        run: dotnet publish ./JobPortal.API/JobPortal.API.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jobportal-api
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jobportal-api
          path: ./publish

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'JobPortalAPI20260522172001'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./publish